"""
architecture_doc.py - 아키텍처 설계서 생성 Agent
──────────────────────────────────────────────────
Bedrock LLM으로 프로젝트 아키텍처 설계서를 HTML로 생성.
"""
import logging
from services.bedrock_client import invoke_model

logger = logging.getLogger(__name__)

_PROMPT = """당신은 AWS 솔루션 아키텍트입니다. MZC Sales Radar 프로젝트의 아키텍처 설계서를 HTML 형식으로 작성해주세요.

프로젝트 개요:
- 메가존클라우드 영업/프리세일즈용 뉴스 인텔리전스 시스템
- AWS Bedrock (Claude + Titan Embed) + AgentCore 기반
- Multi-Agent 파이프라인: 키워드추천→수집→정규화→중복제거→분석→문서생성→저장
- Frontend: Streamlit, Storage: S3 + DynamoDB

아래 섹션을 포함해 HTML로 작성하세요 (h2 태그 사용):

1. Executive Summary
2. Business Pain Point
3. MVP Scope
4. User Journey (영업/프리세일즈 사용자 흐름)
5. Agent Workflow (Orchestrator → 7개 Agent 순서)
6. Agent별 역할 (각 Agent 1~2문장)
7. AWS Architecture (사용 서비스: Bedrock, S3, DynamoDB, AgentCore Runtime)
8. Data Flow (RSS → Normalize → Dedup → Analyze → Score → Briefing)
9. MCP / Tool Calling Design (확장 구조)
10. RAG / Knowledge Base Extension (Bedrock KB 활용 방안)
11. Security & Guardrails (IAM, Guardrails, 민감정보 필터)
12. Observability & Operations (CloudWatch, AgentCore Observability)
13. Failure Handling (RSS실패, Bedrock실패, 저장실패 fallback)
14. MVP vs Production (현재 구현 vs 운영 전환 차이)
15. Demo Scenario (3가지 시나리오)
16. Expected Impact (기대 효과)

Mermaid diagram을 텍스트로 포함해주세요 (```mermaid 블록).
한국어로 작성하세요."""


def generate_architecture_doc() -> str:
    """아키텍처 설계서 HTML 생성."""
    try:
        content = invoke_model(_PROMPT, max_tokens=4096)
    except Exception as e:
        logger.error(f"아키텍처 문서 생성 실패: {e}")
        content = f"<h2>생성 실패</h2><p>{e}</p>"

    html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>MZC Sales Radar - Architecture Document</title>
<style>
body {{ font-family: 'Pretendard', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; line-height: 1.7; }}
h1 {{ color: #FF6B00; border-bottom: 3px solid #FF6B00; padding-bottom: 10px; }}
h2 {{ color: #232F3E; margin-top: 2em; }}
pre {{ background: #f5f5f5; padding: 16px; border-radius: 8px; overflow-x: auto; }}
.footer {{ margin-top: 3em; color: #999; font-size: 0.8em; border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
<h1>MZC Sales Radar - Architecture Document</h1>
{content}
<div class="footer">Generated by MZC Sales Radar | AWS Bedrock + AgentCore</div>
</body>
</html>"""
    return html
